# @no-redirect
POST http://api.eu-pet.com/6/d4/dev_signup
User-Agent: PETKIT DEV
Host: api.eu-pet.com
Content-Type: application/x-www-form-urlencoded

hardware=1&firmware=1.627&mac=0cb8155bd6c8&timezone=1.0&locale=Europe/Berlin&id=400050372&sn=20241202G11724&bt_mac=0cb8155bd6c8&ap_mac=0cb8155bd6c8&chipid=6018761
