< {%
    function generateRandomString(length = 12) {
        const chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
        let result = "";
        for (let i = 0; i < length; i++) {
            result += chars.charAt(Math.floor(Math.random() * chars.length));
        }
        return result;
    }

    function generatePetkitSignature(deviceId, nonce, timestamp, deviceType, secretKey) {
        if (!deviceId || !secretKey) {
            throw new Error("Missing required parameters");
        }
        const signStr = `id${deviceId}nonce${nonce}timestamp${timestamp}type${deviceType}${secretKey}`;
        return crypto.md5().updateWithText(signStr).digest().toHex();
    }

    const nonce = generateRandomString();
    const secretKey = "d7ffd101d72b8e3e";
    const ts = Math.floor(Date.now() / 1000) + 1;
    const id = 400050372;
    const type = 'D4';

    const signature = generatePetkitSignature(id, nonce, ts, type, secretKey);

    request.variables.set("petkitQuery",
        `id=${id}&nonce=${nonce}&timestamp=${ts}&type=${type}&sign=${signature}`);
%}
POST http://api-eu.petkt.com/6/poll/d4/heartbeat
User-Agent: PETKIT DEV
Content-Type: application/x-www-form-urlencoded
X-Device: {{petkitQuery}}

pongokcnt=12&heap=111176&rt=335&code=3&err=-2319
