POST http://localhost:8080/6/d3/dev_state_report
User-Agent: PETKIT DEV
Host: api.eu-pet.com
Content-Type: application/x-www-form-urlencoded
X-Device: id=400002913&nonce=D8ea5O6BGK9l&timestamp=1739098321&type=D3&sign=3e4ee0dc2dece5350ccdffcaf06b4909
