POST https://api-eu.petkt.com/6/d4h/dev_ble_device
User-Agent: PETKIT DEV
X-Device:id=300016346&nonce=dgi2pmil1dic&timestamp=1771158886&type=D4H&sign=92ba2f3fa8d7ae9a45769ed64f0e8188
Content-Type: application/x-www-form-urlencoded
