# @no-redirect
GET http://localhost:8080/6/d4h/dev_signup?mac=fc702ea6e880&sn=20250512D90150&id=300016346&bt_mac=a4c138f3fd25&hardware=1&firmware=810&locale=Europe/Berlin&timezone=1.0&p2pType=2
User-Agent: PETKIT DEV
Host: api.eu-pet.com
Content-Type: application/x-www-form-urlencoded

X-Device: id=300016346&nonce=D8ea5O6BGK9l&timestamp=1739098321&type=D4H&sign=3e4ee0dc2dece5350ccdffcaf06b4909

